### ISSUE TITLE
Create binutils-2.40 compatible pahole release?

### ISSUE THREAD

**Issue by trofi** [acmel/dwarves#37]
`nixpkgs` would eventually like to update `binutils` to `2.40` as a default toolchain (https://github.com/NixOS/nixpkgs/pull/211126).

I think we need newer `pahole` release to support `binutils-2.40` which started generating
fresh DWARF tags that pahole-1.24 does not yet understand and fails as:

    $ nix log /nix/store/ckjr3sbsh13y1prigppk2y0jpf0p4icm-linux-6.1.6.drv
    ...
      BTF     .btf.vmlinux.bin.o
      Unsupported DW_TAG_unspecified_type(0x3b)
      Encountered error while encoding BTF.

Upstream thread to add the support for it:
    https://lore.kernel.org/all/YzwkazNc6wNCpQTN@kernel.org/t/

`master` branch of `pahole` seems to build `linux` kernels successfully.

Thanks!

**Comment by acmel** [comment]
Please consider using the backported patches made available here:

http://vger.kernel.org/~acme/pahole/rpms/1.24+DW_TAG_unspecified_type/SRPMS/dwarves-1.24-3.fc39.src.rpm

There were some last minute issues that prevented me from cutting 1.25, it should be soon, but using the backport present in the above src.rpm may be an stop gap solution, that is what was done with both Fedora rawhide and OpenSuse Tumbleweed.

**Comment by trofi** [comment]
`.src.rpm` is a bit clunky to integrate into build systems for non-rpm-based distributions.

`nixpkgs` ended up using random (02d67c51765dfbd5893087da63744c864c7cc9e0 `Mon Oct 24 11:25:44 2022`) `master` commit. It is successfully building our kernels for a few months, thus it's not an immediate blocker for `binutils-2.40` update.

But getting an official release tarball would still help align the distributions.

**Comment by thesamesam** [comment]
Yeah, really, if it's good enough to use in fedora and opensuse and to recommend to other distros, it's worth a release even if imperfect.

**Comment by martinetd** [comment]
For follow-up: commit 02d67c5 failed to build linux 6.3-rc1, the latest commit a9498899109d3be14f17abbc322a8f55a1067bee fixed the issue.

I didn't get out of my way to check if the 1.24-3.fc39 src.rpm has the same problem (I guess you'll hear about it soon enough if so), but while not bringing much to the table I second other comments here: it's easy to make a 1.24 branch and tag 1.24.1 with the 7 patches in https://src.fedoraproject.org/rpms/dwarves/tree/rawhide and would likely have helped. At least it'd be more obvious for you if a9498899 is needed and we'd get a 1.24.2 ;D

**Comment by acmel** [comment]
Please consider using the backported patches made available here:

http://vger.kernel.org/~acme/pahole/rpms/1.24+DW_TAG_unspecified_type/SRPMS/dwarves-1.24-3.fc39.src.rpm

There were some last minute issues that prevented me from cutting 1.25, it should be soon, but using the backport present in the above src.rpm may be an stop gap solution, that is what was done with both Fedora rawhide and OpenSuse Tumbleweed.

**Comment by acmel** [comment]
1.25 was released.

**Comment by trofi** [comment]
Thank you!
