### ISSUE TITLE
Pahole 1.27 breaks LLVM compiled kernels compilation

### ISSUE THREAD

**Issue by ptr1337** [acmel/dwarves#53]
Hi,

Just wanted to forward it here also to here.

Currently, the Clang compiled kernel fails due pahole 1.27.

to avoid such issues in the futures, how about doing additional tests for clang compiled kernels?

See:
https://gitlab.archlinux.org/archlinux/packaging/packages/pahole/-/issues/1

**Comment by ptr1337** [comment]
@acmel 

Thanks for the commit. Ive also verified and tested this. Works without problems.
Thanks!

Tested-by: Peter Jung <ptr1337@cachyos.org>

**Comment by martinetd** [comment]
For follow up that commit wasn't enough and this needed https://github.com/acmel/dwarves/commit/94a01bde592c555b3eb526aeb4c2ad695c5660d8.patch as well - a user on nixos reported our update broke this as I hadn't backported the second patch.

In the future it'd be great if a release could be cut with just fix patches (v1.27.1 or something) when there are such breakages so each distro won't have to cherry-pick such patches independently; clang builds aren't tested thoroughly enough yet.
