### ISSUE TITLE
JSON backend support

### ISSUE THREAD

**Issue by Abyss-W4tcher** [acmel/dwarves#56]
Hi, 

To share and store dumped BTF information in a structured manner, I am looking for a way to convert the data produced by `pahole` into JSON format. Is there ongoing work on this subject ? 
The goal would be to have each struct referenced under a `structs` parent key, and each member being referenced by properties : name, kind (pointer, enum, int...), offset, size etc. 

Thanks for this amazing tool !

**Comment by alan-maguire** [comment]
There is support in bpftool to do this, but for a .BTF section as a whole rather than for a specific struct, e.g.

bpftool -j btf dump file /sys/kernel/btf/vmlinux

Does that fit your needs?

**Comment by Abyss-W4tcher** [comment]
Awesome, thanks ! :)
